const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

exports.generateReportPDF = async (report) => {
  return new Promise((resolve, reject) => {
    try {
      // Ensure pdfs directory exists
      const pdfsDir = path.join(__dirname, '..', '..', 'uploads', 'pdfs');
      if (!fs.existsSync(pdfsDir)) {
        fs.mkdirSync(pdfsDir, { recursive: true });
      }

      const fileName = `report-${report._id}.pdf`;
      const filePath = path.join(pdfsDir, fileName);
      const relativePath = `/uploads/pdfs/${fileName}`;

      const doc = new PDFDocument({ margin: 50 });
      const stream = fs.createWriteStream(filePath);
      
      doc.pipe(stream);

      // --- Header ---
      const clinicName = report.clinic && report.clinic.name ? report.clinic.name : 'Nexovision Clinic';
      doc.fontSize(20).font('Helvetica-Bold').text(clinicName, { align: 'center' });
      doc.fontSize(10).font('Helvetica').text('Automated Medical Imaging Diagnostic Report', { align: 'center' });
      doc.fontSize(8).font('Helvetica-Oblique').text('Powered by Nexovision', { align: 'center' });
      doc.moveDown();
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
      doc.moveDown();

      // --- Patient & Scan Info ---
      doc.fontSize(14).font('Helvetica-Bold').text('Patient Information');
      doc.fontSize(10).font('Helvetica');
      doc.text(`Name: ${report.patient.firstName} ${report.patient.lastName}`);
      doc.text(`ID: ${report.patient._id}`);
      doc.text(`DOB: ${new Date(report.patient.dateOfBirth).toLocaleDateString()}`);
      doc.text(`Gender: ${report.patient.gender}`);
      doc.moveDown();

      doc.fontSize(14).font('Helvetica-Bold').text('Scan Details');
      doc.fontSize(10).font('Helvetica');
      doc.text(`Modality: ${report.scan.imageType.toUpperCase()}`);
      doc.text(`Body Part: ${report.scan.bodyPart}`);
      doc.text(`Date of Scan: ${new Date(report.scan.createdAt).toLocaleDateString()}`);
      doc.text(`Report Generated By: ${report.generatedBy.name}`);
      doc.moveDown();
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
      doc.moveDown();

      // --- Findings ---
      if (report.structuredFindings) {
        const sf = report.structuredFindings;
        
        doc.fontSize(14).font('Helvetica-Bold').text('Overall Impression');
        doc.fontSize(10).font('Helvetica').text(sf.impression || 'N/A', { align: 'justify' });
        doc.moveDown();

        doc.fontSize(14).font('Helvetica-Bold').text('Detailed Findings');
        if (sf.findings && sf.findings.length > 0) {
          sf.findings.forEach(f => {
            doc.fontSize(10).font('Helvetica-Bold').text(`${f.region} (Severity: ${f.severity})`);
            doc.font('Helvetica').text(f.description, { align: 'justify' });
            doc.moveDown(0.5);
          });
        } else {
          doc.fontSize(10).font('Helvetica').text('No detailed findings recorded.');
        }
        doc.moveDown();

        if (sf.differentialDiagnosis && sf.differentialDiagnosis.length > 0) {
          doc.fontSize(14).font('Helvetica-Bold').text('Differential Diagnosis');
          sf.differentialDiagnosis.forEach(d => {
            doc.fontSize(10).font('Helvetica').text(`• ${d}`);
          });
          doc.moveDown();
        }

        if (sf.recommendations && sf.recommendations.length > 0) {
          doc.fontSize(14).font('Helvetica-Bold').text('Recommendations');
          sf.recommendations.forEach(r => {
            doc.fontSize(10).font('Helvetica').text(`• ${r}`);
          });
          doc.moveDown();
        }
      } else {
        // Fallback to raw text
        doc.fontSize(14).font('Helvetica-Bold').text('Findings');
        doc.fontSize(10).font('Helvetica').text(report.aiFindingsRaw, { align: 'justify' });
        doc.moveDown();
      }

      // --- Doctor Notes ---
      if (report.doctorNotes) {
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown();
        doc.fontSize(14).font('Helvetica-Bold').text("Doctor's Clinical Addendum");
        doc.fontSize(10).font('Helvetica').text(report.doctorNotes, { align: 'justify' });
        doc.moveDown();
      }

      // --- Footer / Disclaimer ---
      doc.moveDown(2);
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
      doc.moveDown();
      doc.fontSize(8).font('Helvetica-Oblique').text(
        'DISCLAIMER: This report was generated with the assistance of Nexovision AI. It is intended to support, not replace, the clinical judgment of a qualified healthcare professional. All findings must be clinically correlated.',
        { align: 'center', width: 500 }
      );
      
      if (report.status === 'finalized' && report.reviewedBy) {
        doc.moveDown();
        doc.text(`Electronically Reviewed and Finalized by: ${report.reviewedBy.name} on ${new Date(report.reviewedAt).toLocaleString()}`, { align: 'center' });
      }

      doc.end();

      stream.on('finish', () => {
        resolve(relativePath);
      });

      stream.on('error', (err) => {
        reject(err);
      });
      
    } catch (error) {
      reject(error);
    }
  });
};
