const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

exports.generateReportPDF = async (report) => {
  return new Promise(async (resolve, reject) => {
    try {
      // Ensure pdfs directory exists
      const pdfsDir = path.join(__dirname, '..', '..', 'uploads', 'pdfs');
      if (!fs.existsSync(pdfsDir)) {
        fs.mkdirSync(pdfsDir, { recursive: true });
      }

      const fileName = `report-${report._id}.pdf`;
      const filePath = path.join(pdfsDir, fileName);
      const relativePath = `/uploads/pdfs/${fileName}`;

      // Set margins to leave space for absolute header and footer on every page
      const doc = new PDFDocument({ 
        margins: { top: 120, bottom: 100, left: 50, right: 50 },
        bufferPages: true 
      });
      
      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      // --- Patient & Scan Info ---
      const infoStartY = doc.y;

      // Draw Images on the right (Grid/Collage)
      const files = report.scan.files && report.scan.files.length > 0 ? report.scan.files : (report.scan.filePath ? [{ filePath: report.scan.filePath }] : []);
      const imagesToDraw = files.slice(0, 4);

      if (imagesToDraw.length > 0) {
        const sharp = require('sharp');
        
        if (imagesToDraw.length === 1) {
          const pth = path.join(__dirname, '..', '..', imagesToDraw[0].filePath);
          if (fs.existsSync(pth)) {
            try {
              const imgBuffer = await sharp(pth).jpeg().toBuffer();
              doc.image(imgBuffer, 400, infoStartY, { fit: [120, 120] });
            } catch (err) { console.error(err); }
          }
        } else {
          // Grid layout
          const positions = [
            { x: 400, y: infoStartY },
            { x: 462, y: infoStartY },
            { x: 400, y: infoStartY + 62 },
            { x: 462, y: infoStartY + 62 }
          ];
          for (let i = 0; i < imagesToDraw.length; i++) {
            const pth = path.join(__dirname, '..', '..', imagesToDraw[i].filePath);
            if (fs.existsSync(pth)) {
              try {
                const imgBuffer = await sharp(pth).jpeg().toBuffer();
                doc.image(imgBuffer, positions[i].x, positions[i].y, { fit: [58, 58] });
              } catch (err) { console.error(err); }
            }
          }
        }
      }

      doc.y = infoStartY;
      doc.fontSize(14).font('Helvetica-Bold').text('Patient Information');
      doc.fontSize(10).font('Helvetica');
      doc.text(`Name: ${report.patient.firstName} ${report.patient.lastName}`);
      doc.text(`ID: ${report.patient._id}`);
      doc.text(`DOB: ${new Date(report.patient.dateOfBirth).toLocaleDateString()}`);
      doc.text(`Gender: ${report.patient.gender}`);
      doc.moveDown();

      doc.fontSize(14).font('Helvetica-Bold').text('Scan Details');
      doc.fontSize(10).font('Helvetica');
      doc.text(`Modality: ${report.scan.imageType.toUpperCase()}`);
      doc.text(`Body Part: ${report.scan.bodyPart}`);
      doc.text(`Date of Scan: ${new Date(report.scan.createdAt).toLocaleDateString()}`);
      doc.text(`Report Generated By: ${report.generatedBy.name}`);
      
      const imageBottom = infoStartY + 130; 
      if (doc.y < imageBottom) {
         doc.y = imageBottom;
      } else {
         doc.moveDown();
      }
      
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
      doc.moveDown();

      // --- Findings ---
      if (report.structuredFindings) {
        const sf = report.structuredFindings;
        
        doc.fontSize(14).font('Helvetica-Bold').text('Overall Impression');
        doc.fontSize(10).font('Helvetica').text(sf.impression || 'N/A', { align: 'justify' });
        doc.moveDown();

        doc.fontSize(14).font('Helvetica-Bold').text('Detailed Findings');
        if (sf.findings && sf.findings.length > 0) {
          sf.findings.forEach(f => {
            doc.fontSize(10).font('Helvetica-Bold').text(`${f.region} (Severity: ${f.severity})`);
            doc.font('Helvetica').text(f.description, { align: 'justify' });
            doc.moveDown(0.5);
          });
        } else {
          doc.fontSize(10).font('Helvetica').text('No detailed findings recorded.');
        }
        doc.moveDown();

        if (sf.differentialDiagnosis && sf.differentialDiagnosis.length > 0) {
          doc.fontSize(14).font('Helvetica-Bold').text('Differential Diagnosis');
          sf.differentialDiagnosis.forEach(d => {
            doc.fontSize(10).font('Helvetica').text(`• ${d}`);
          });
          doc.moveDown();
        }

        if (sf.recommendations && sf.recommendations.length > 0) {
          doc.fontSize(14).font('Helvetica-Bold').text('Recommendations');
          sf.recommendations.forEach(r => {
            doc.fontSize(10).font('Helvetica').text(`• ${r}`);
          });
          doc.moveDown();
        }
      } else {
        // Fallback to raw text
        doc.fontSize(14).font('Helvetica-Bold').text('Findings');
        doc.fontSize(10).font('Helvetica').text(report.aiFindingsRaw, { align: 'justify' });
        doc.moveDown();
      }

      // --- Doctor Notes ---
      if (report.doctorNotes) {
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown();
        doc.fontSize(14).font('Helvetica-Bold').text("Doctor's Clinical Addendum");
        doc.fontSize(10).font('Helvetica').text(report.doctorNotes, { align: 'justify' });
        doc.moveDown();
      }

      // --- Global Header & Footer (Applied to all buffered pages) ---
      const range = doc.bufferedPageRange();
      const clinicName = report.clinic && report.clinic.name ? report.clinic.name : 'Nexovision Clinic';

      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        
        // Prevent PDFKit from creating new pages when drawing in the margins
        const oldBottom = doc.page.margins.bottom;
        const oldTop = doc.page.margins.top;
        doc.page.margins.bottom = 0;
        doc.page.margins.top = 0;
        
        // Header
        doc.fontSize(20).font('Helvetica-Bold').text(clinicName, 50, 50, { align: 'center', width: 500, lineBreak: false });
        doc.fontSize(10).font('Helvetica').text('Automated Medical Imaging Diagnostic Report', 50, 75, { align: 'center', width: 500, lineBreak: false });
        doc.fontSize(8).font('Helvetica-Oblique').text('Powered by Nexovision', 50, 90, { align: 'center', width: 500, lineBreak: false });
        doc.moveTo(50, 105).lineTo(550, 105).stroke();

        // Footer
        doc.moveTo(50, 700).lineTo(550, 700).stroke();
        doc.fontSize(8).font('Helvetica-Oblique').text(
          'DISCLAIMER: This report was generated with the assistance of Nexovision AI. It is intended to support, not replace, the clinical judgment of a qualified healthcare professional. All findings must be clinically correlated.',
          50, 710, { align: 'center', width: 500, lineBreak: false }
        );
        
        if (report.status === 'finalized' && report.reviewedBy) {
          doc.text(`Electronically Reviewed and Finalized by: ${report.reviewedBy.name} on ${new Date(report.reviewedAt).toLocaleString()}`, 50, 740, { align: 'center', width: 500, lineBreak: false });
        }
        
        // Page numbers
        doc.fontSize(8).font('Helvetica').text(`Page ${i + 1} of ${range.count}`, 50, 760, { align: 'center', width: 500, lineBreak: false });
        
        doc.page.margins.bottom = oldBottom;
        doc.page.margins.top = oldTop;
      }

      doc.end();

      stream.on('finish', () => {
        resolve(relativePath);
      });

      stream.on('error', (err) => {
        reject(err);
      });
      
    } catch (error) {
      reject(error);
    }
  });
};
